#Database settings
spring:
  main.allow-circular-references: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/mdd
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # fileupload
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

#JWT Security
mdd.api:
  lifespan: 9999 #jwt duration in minutes
  secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBB11111111111111111111111111111
  dev-url: ${server.servlet.context-path}/
  prod-url: test.com
  files-upload: files-upload

#Server settings
server:
  port: 3002
  servlet.context-path: /api

#Logging levels
logging:
  level:
    root: ERROR
    mdd.api: INFO
    org.springframework.boot.web.embedded.tomcat: INFO
  file:
    path: logs/
    max-history: 5